import { useEffect, useState } from "react";
import { create, getAll, remove, update } from "../../api/api";
import ConfirmDialog from "../../components/ConfirmDialog";
import FormModal from "../../components/FormModal";

const tabs = [
  { key: "surveyors", label: "Surveyors" }, { key: "surveyTypes", label: "Survey types" }, { key: "scores", label: "Scores" },
  { key: "riskRating", label: "Risk ratings" }, { key: "surveyorCertStatus", label: "Certification status" }, { key: "specializations", label: "Specialisations" },
];
const inputClass = "mt-1.5 w-full rounded-lg border border-[#c9ddd9] px-3 py-2.5 text-sm outline-none focus:border-[#087c77] focus:ring-2 focus:ring-teal-100";
const labels = { surveyTypes: "Survey type", scores: "Score", riskRating: "Risk rating", surveyorCertStatus: "Certification status", specializations: "Specialisation" };

function SurveySetupPage() {
  const [activeTab, setActiveTab] = useState("surveyors");
  const [data, setData] = useState({});
  const [users, setUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [form, setForm] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [error, setError] = useState("");
  const resources = tabs.map((tab) => tab.key);

  const load = async () => {
    try {
      setLoading(true);
      const [responses, usersResponse] = await Promise.all([Promise.all(resources.map((resource) => getAll(resource))), getAll("users")]);
      setData(Object.fromEntries(resources.map((resource, index) => [resource, responses[index].data])));
      setUsers(usersResponse.data);
      setError("");
    } catch (err) { setError("We couldn't load the survey setup data."); console.error(err); }
    finally { setLoading(false); }
  };
  useEffect(() => { load(); }, []);
  const records = data[activeTab] || [];
  const title = activeTab === "surveyors" ? "Surveyor registry" : labels[activeTab];
  const save = async (payload) => { try { if (form.record) await update(activeTab, form.record[identifier(activeTab)], payload); else await create(activeTab, payload); setForm(null); await load(); } catch (err) { console.error(err); } };
  const confirmDelete = async () => { try { await remove(activeTab, deleting[identifier(activeTab)]); setDeleting(null); await load(); } catch (err) { console.error(err); } };

  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:py-8"><header className="rounded-2xl border border-[#cde5e0] bg-[linear-gradient(125deg,#e8f5f3_0%,#f8fbfa_65%,#fdf7ea_100%)] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">Survey administration</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#143c42]">Survey setup</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#527076]">Maintain the people and controlled reference data required to create and complete accreditation surveys.</p></header>{error && <p className="mt-5 text-sm text-red-700">{error}</p>}<div className="mt-6 flex gap-1 overflow-x-auto border-b border-[#d6e5e2]">{tabs.map((tab) => <button key={tab.key} onClick={() => setActiveTab(tab.key)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-semibold ${activeTab === tab.key ? "border-[#087c77] text-[#087c77]" : "border-transparent text-[#668187] hover:text-[#087c77]"}`}>{tab.label}</button>)}</div><section className="mt-6 overflow-hidden rounded-xl border border-[#e2ecea] bg-white shadow-[0_8px_24px_rgba(20,60,66,0.06)]"><div className="flex flex-col gap-3 border-b border-[#e1ecea] p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold text-[#143c42]">{title}</h2><p className="mt-1 text-sm text-[#668187]">Only Administrators can maintain these records.</p></div><button onClick={() => setForm({ record: null })} className="rounded-lg bg-[#087c77] px-4 py-2.5 text-sm font-semibold text-white hover:bg-[#05635f]">+ Add {activeTab === "surveyors" ? "surveyor" : labels[activeTab].toLowerCase()}</button></div>{loading ? <div className="space-y-3 p-6">{[1,2,3].map((item) => <div key={item} className="h-14 animate-pulse rounded bg-slate-100" />)}</div> : <SetupTable type={activeTab} records={records} onEdit={(record) => setForm({ record })} onDelete={setDeleting} />}</section><FormModal open={!!form} onClose={() => setForm(null)}>{form && <SetupForm type={activeTab} record={form.record} data={data} users={users} onSubmit={save} onCancel={() => setForm(null)} />}</FormModal><ConfirmDialog open={!!deleting} title={`Delete ${activeTab === "surveyors" ? "Surveyor" : labels[activeTab]}`} message="Are you sure you want to delete this record? It may be in use by existing surveys or assessments." onConfirm={confirmDelete} onCancel={() => setDeleting(null)} /></main>;
}

const identifier = (type) => ({ surveyors: "surveyorId", surveyTypes: "surveyTypeId", scores: "scoreId", riskRating: "riskId", surveyorCertStatus: "surveyorCertStatusId", specializations: "specializationId" }[type]);
function SetupTable({ type, records, onEdit, onDelete }) { if (!records.length) return <p className="p-10 text-center text-sm text-[#668187]">No records yet.</p>; const cells = (record) => type === "surveyors" ? [`${record.firstName} ${record.lastName}`, record.surveyorCertStatusName, record.specializationName] : type === "scores" ? [record.scoreLabel, record.scoreValue ?? "N/A", record.description] : type === "riskRating" ? [record.riskLabel, record.riskValue, record.severityOrder ?? "—", record.description] : [record[`${type === "surveyTypes" ? "surveyType" : type === "surveyorCertStatus" ? "surveyorCertStatus" : "specialization"}Name`], record.description]; return <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-b border-[#dce9e7] bg-[#f5faf9] text-xs uppercase tracking-wider text-[#527076]"><tr>{(type === "surveyors" ? ["Name", "Certification", "Specialisation"] : type === "scores" ? ["Label", "Value", "Description"] : type === "riskRating" ? ["Label", "Value", "Order", "Description"] : ["Name", "Description"]).map((heading) => <th key={heading} className="px-5 py-3.5">{heading}</th>)}<th className="px-5 py-3.5 text-right">Actions</th></tr></thead><tbody className="divide-y divide-[#e7efed]">{records.map((record) => <tr key={record[identifier(type)]} className="hover:bg-[#f5fbfa]">{cells(record).map((value, index) => <td key={index} className="px-5 py-4 text-[#527076]">{value === 0 ? 0 : value || "—"}</td>)}<td className="px-5 py-4 text-right"><div className="flex justify-end gap-2"><button onClick={() => onEdit(record)} className="rounded-md border border-[#b9d6d1] px-3 py-1.5 text-xs font-semibold text-[#087c77] hover:bg-teal-50">Edit</button><button onClick={() => onDelete(record)} className="rounded-md border border-red-200 px-3 py-1.5 text-xs font-semibold text-red-700 hover:bg-red-50">Delete</button></div></td></tr>)}</tbody></table></div>; }

function SetupForm({ type, record, data, users, onSubmit, onCancel }) { const [form, setForm] = useState(initial(type, record)); const change = (event) => setForm({ ...form, [event.target.name]: event.target.value }); const submit = (event) => { event.preventDefault(); onSubmit(payload(type, form)); }; if (type === "surveyors") { const assigned = new Set((data.surveyors || []).filter((item) => item.surveyorId !== record?.surveyorId).map((item) => item.userId)); return <form onSubmit={submit}><Heading title={record ? "Edit surveyor" : "Add surveyor"} /><div className="mt-5 space-y-4">{!record && <Select label="User" name="userId" value={form.userId} change={change} options={users.filter((user) => !assigned.has(user.userId)).map((user) => ({ value: user.userId, label: `${user.firstName} ${user.lastName} (${user.username})` }))} />}<Select label="Certification status" name="surveyorCertStatusId" value={form.surveyorCertStatusId} change={change} options={(data.surveyorCertStatus || []).map((item) => ({ value: item.surveyorCertStatusId, label: item.surveyorCertStatusName }))} /><Select label="Specialisation" name="specializationId" value={form.specializationId} change={change} options={(data.specializations || []).map((item) => ({ value: item.specializationId, label: item.specializationName }))} /></div><Actions onCancel={onCancel} /></form>; } const fields = type === "scores" ? [["scoreLabel", "Score label", "text"], ["scoreValue", "Score value (leave blank for N/A)", "number"], ["description", "Description", "text"]] : type === "riskRating" ? [["riskLabel", "Risk label", "text"], ["riskValue", "Risk value", "text"], ["severityOrder", "Severity order", "number"], ["description", "Description", "text"]] : [[type === "surveyTypes" ? "surveyTypeName" : type === "surveyorCertStatus" ? "surveyorCertStatusName" : "specializationName", "Name", "text"], ["description", "Description", "text"]]; return <form onSubmit={submit}><Heading title={`${record ? "Edit" : "Add"} ${labels[type]}`} /><div className="mt-5 space-y-4">{fields.map(([name, label, fieldType]) => <label key={name} className="block text-sm font-semibold text-[#143c42]">{label}<input required={!["description", "scoreValue", "severityOrder"].includes(name)} name={name} type={fieldType} value={form[name] ?? ""} onChange={change} className={inputClass} /></label>)}</div><Actions onCancel={onCancel} /></form>; }
function initial(type, record) { if (type === "surveyors") return { userId: record?.userId || "", surveyorCertStatusId: record?.surveyorCertStatusId || "", specializationId: record?.specializationId || "" }; if (type === "scores") return { scoreLabel: record?.scoreLabel || "", scoreValue: record?.scoreValue ?? "", description: record?.description || "" }; if (type === "riskRating") return { riskLabel: record?.riskLabel || "", riskValue: record?.riskValue || "", severityOrder: record?.severityOrder ?? "", description: record?.description || "" }; const name = type === "surveyTypes" ? "surveyTypeName" : type === "surveyorCertStatus" ? "surveyorCertStatusName" : "specializationName"; return { [name]: record?.[name] || "", description: record?.description || "" }; }
function payload(type, form) { if (type === "surveyors") return { userId: Number(form.userId), surveyorCertStatusId: Number(form.surveyorCertStatusId), specializationId: Number(form.specializationId) }; if (type === "scores") return { scoreLabel: form.scoreLabel.trim(), scoreValue: form.scoreValue === "" ? null : Number(form.scoreValue), description: form.description.trim() || null }; if (type === "riskRating") return { riskLabel: form.riskLabel.trim(), riskValue: form.riskValue.trim(), severityOrder: form.severityOrder === "" ? null : Number(form.severityOrder), description: form.description.trim() || null }; const name = type === "surveyTypes" ? "surveyTypeName" : type === "surveyorCertStatus" ? "surveyorCertStatusName" : "specializationName"; return { [name]: form[name].trim(), description: form.description.trim() || null }; }
function Heading({ title }) { return <><p className="text-xs font-bold uppercase tracking-[0.16em] text-teal-700">Survey setup</p><h2 className="mt-1 text-xl font-bold text-[#143c42]">{title}</h2></>; }
function Select({ label, name, value, change, options }) { return <label className="block text-sm font-semibold text-[#143c42]">{label}<select required name={name} value={value} onChange={change} className={inputClass}><option value="">Select {label.toLowerCase()}</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function Actions({ onCancel }) { return <div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onCancel} className="rounded-lg px-4 py-2.5 text-sm font-semibold text-[#527076]">Cancel</button><button type="submit" className="rounded-lg bg-[#087c77] px-4 py-2.5 text-sm font-semibold text-white">Save</button></div>; }
export default SurveySetupPage;
