FROM mcr.microsoft.com/dotnet/sdk:10.0
RUN dotnet tool install --global dotnet-ef --version 10.0.10
ENV PATH="${PATH}:/root/.dotnet/tools"
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
