// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260917001149_AddSurveyActionItems")]
    partial class AddSurveyActionItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Accounts.RefreshToken", b =>
                {
                    b.Property<int>("refreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("refreshTokenId"));

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("revokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("tokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userAccountId")
                        .HasColumnType("integer");

                    b.HasKey("refreshTokenId");

                    b.HasIndex("tokenHash")
                        .IsUnique();

                    b.HasIndex("userAccountId");

                    b.ToTable("refreshTokens");
                });

            modelBuilder.Entity("backend.Models.Accounts.Role", b =>
                {
                    b.Property<int>("roleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roleId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("roleId");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("backend.Models.Accounts.User", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userId"));

                    b.Property<string>("comments")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("mobile")
                        .HasColumnType("text");

                    b.Property<int>("organizationId")
                        .HasColumnType("integer");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("position")
                        .HasColumnType("text");

                    b.Property<int>("userAccountId")
                        .HasColumnType("integer");

                    b.HasKey("userId");

                    b.HasIndex("organizationId");

                    b.HasIndex("userAccountId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("backend.Models.Accounts.UserAccount", b =>
                {
                    b.Property<int>("userAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userAccountId"));

                    b.Property<DateOnly>("dateCreated")
                        .HasColumnType("date");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("roleId")
                        .HasColumnType("integer");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("userAccountId");

                    b.HasIndex("roleId");

                    b.ToTable("userAccounts");
                });

            modelBuilder.Entity("backend.Models.Assessment.ComplianceAssessment", b =>
                {
                    b.Property<int>("complianceAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("complianceAssessmentId"));

                    b.Property<string>("complianceComments")
                        .HasColumnType("text");

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<int?>("riskRatingId")
                        .HasColumnType("integer");

                    b.Property<int?>("scoreId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyorId")
                        .HasColumnType("integer");

                    b.HasKey("complianceAssessmentId");

                    b.HasIndex("complianceId");

                    b.HasIndex("riskRatingId");

                    b.HasIndex("scoreId");

                    b.HasIndex("surveyorId");

                    b.HasIndex("surveyId", "complianceId")
                        .IsUnique();

                    b.ToTable("complianceAssessments");
                });

            modelBuilder.Entity("backend.Models.Assessment.ComplianceEvidenceCheck", b =>
                {
                    b.Property<int>("complianceEvidenceCheckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("complianceEvidenceCheckId"));

                    b.Property<int>("complianceAssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("evidenceId")
                        .HasColumnType("integer");

                    b.Property<bool>("isChecked")
                        .HasColumnType("boolean");

                    b.HasKey("complianceEvidenceCheckId");

                    b.HasIndex("complianceAssessmentId");

                    b.HasIndex("evidenceId");

                    b.ToTable("complianceEvidenceChecks");
                });

            modelBuilder.Entity("backend.Models.Facilities.Category", b =>
                {
                    b.Property<int>("categoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("categoryId"));

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.HasKey("categoryId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("backend.Models.Facilities.CreditationStatus", b =>
                {
                    b.Property<int>("creditationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("creditationStatusId"));

                    b.Property<string>("comments")
                        .HasColumnType("text");

                    b.Property<string>("creditationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("creditationStatusId");

                    b.ToTable("creditationStatuses");
                });

            modelBuilder.Entity("backend.Models.Facilities.Facility", b =>
                {
                    b.Property<int>("facilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("facilityId"));

                    b.Property<string>("comments")
                        .HasColumnType("text");

                    b.Property<int>("creditationStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("districtId")
                        .HasColumnType("integer");

                    b.Property<string>("facilityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("headOfService")
                        .HasColumnType("text");

                    b.Property<int>("levelId")
                        .HasColumnType("integer");

                    b.Property<int>("organizationId")
                        .HasColumnType("integer");

                    b.HasKey("facilityId");

                    b.HasIndex("creditationStatusId");

                    b.HasIndex("districtId");

                    b.HasIndex("levelId");

                    b.HasIndex("organizationId");

                    b.ToTable("facilities");
                });

            modelBuilder.Entity("backend.Models.Facilities.Level", b =>
                {
                    b.Property<int>("levelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("levelId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("levelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("levelOrder")
                        .HasMaxLength(1)
                        .HasColumnType("integer");

                    b.HasKey("levelId");

                    b.ToTable("levels");
                });

            modelBuilder.Entity("backend.Models.Facilities.Organization", b =>
                {
                    b.Property<int>("organizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("organizationId"));

                    b.Property<int>("categoryId")
                        .HasColumnType("integer");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("organizationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("organizationId");

                    b.HasIndex("categoryId");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Specialization", b =>
                {
                    b.Property<int>("specializationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("specializationId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("specializationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("specializationId");

                    b.ToTable("specializations");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Survey", b =>
                {
                    b.Property<int>("surveyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyId"));

                    b.Property<string>("cancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("cancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("cancelledByUsername")
                        .HasColumnType("text");

                    b.Property<DateOnly>("endDate")
                        .HasColumnType("date");

                    b.Property<int>("facilityId")
                        .HasColumnType("integer");

                    b.Property<bool>("isCancelled")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("startDate")
                        .HasColumnType("date");

                    b.Property<int>("surveyTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyorId")
                        .HasColumnType("integer");

                    b.HasKey("surveyId");

                    b.HasIndex("facilityId");

                    b.HasIndex("surveyTypeId");

                    b.HasIndex("surveyorId");

                    b.ToTable("surveys");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyStandardAssignment", b =>
                {
                    b.Property<int>("surveyStandardAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyStandardAssignmentId"));

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyorId")
                        .HasColumnType("integer");

                    b.HasKey("surveyStandardAssignmentId");

                    b.HasIndex("standardId");

                    b.HasIndex("surveyorId");

                    b.HasIndex("surveyId", "standardId")
                        .IsUnique();

                    b.ToTable("surveyStandardAssignments");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", b =>
                {
                    b.Property<int>("surveyToolkitSnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitSnapshotId"));

                    b.Property<string>("customisationReason")
                        .HasColumnType("text");

                    b.Property<string>("scopeType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<string>("templateSummary")
                        .HasColumnType("text");

                    b.HasKey("surveyToolkitSnapshotId");

                    b.HasIndex("surveyId")
                        .IsUnique();

                    b.ToTable("surveyToolkitSnapshots");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshotCompliance", b =>
                {
                    b.Property<int>("surveyToolkitSnapshotComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitSnapshotComplianceId"));

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyToolkitSnapshotId")
                        .HasColumnType("integer");

                    b.HasKey("surveyToolkitSnapshotComplianceId");

                    b.HasIndex("complianceId");

                    b.HasIndex("surveyToolkitSnapshotId", "complianceId")
                        .IsUnique();

                    b.ToTable("surveyToolkitSnapshotCompliances");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshotStandard", b =>
                {
                    b.Property<int>("surveyToolkitSnapshotStandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitSnapshotStandardId"));

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyToolkitSnapshotId")
                        .HasColumnType("integer");

                    b.HasKey("surveyToolkitSnapshotStandardId");

                    b.HasIndex("standardId");

                    b.HasIndex("surveyToolkitSnapshotId", "standardId")
                        .IsUnique();

                    b.ToTable("surveyToolkitSnapshotStandards");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplate", b =>
                {
                    b.Property<int>("surveyToolkitTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitTemplateId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<bool>("isActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("isServiceOverlay")
                        .HasColumnType("boolean");

                    b.Property<int?>("levelId")
                        .HasColumnType("integer");

                    b.Property<string>("templateName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("templateVersion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("surveyToolkitTemplateId");

                    b.HasIndex("levelId");

                    b.ToTable("surveyToolkitTemplates");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplateCompliance", b =>
                {
                    b.Property<int>("surveyToolkitTemplateComplianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitTemplateComplianceId"));

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyToolkitTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("surveyToolkitTemplateComplianceId");

                    b.HasIndex("complianceId");

                    b.HasIndex("surveyToolkitTemplateId", "complianceId")
                        .IsUnique();

                    b.ToTable("surveyToolkitTemplateCompliances");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplateStandard", b =>
                {
                    b.Property<int>("surveyToolkitTemplateStandardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyToolkitTemplateStandardId"));

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyToolkitTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("surveyToolkitTemplateStandardId");

                    b.HasIndex("standardId");

                    b.HasIndex("surveyToolkitTemplateId", "standardId")
                        .IsUnique();

                    b.ToTable("surveyToolkitTemplateStandards");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyType", b =>
                {
                    b.Property<int>("surveyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyTypeId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("surveyTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("surveyTypeId");

                    b.ToTable("surveyTypes");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyorCertStatus", b =>
                {
                    b.Property<int>("surveyorCertStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyorCertStatusId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("surveyorCertStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("surveyorCertStatusId");

                    b.ToTable("surveyorCertStatuses");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Surveyors", b =>
                {
                    b.Property<int>("surveyorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyorId"));

                    b.Property<int>("specializationId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyorCertStatusId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("surveyorId");

                    b.HasIndex("specializationId");

                    b.HasIndex("surveyorCertStatusId");

                    b.HasIndex("userId")
                        .IsUnique();

                    b.ToTable("surveyors");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Property<int>("complianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("complianceId"));

                    b.Property<string>("complianceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("complianceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("criterionId")
                        .HasColumnType("integer");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("complianceId");

                    b.HasIndex("criterionId", "complianceNumber")
                        .IsUnique();

                    b.ToTable("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Property<int>("componentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("componentId"));

                    b.Property<string>("componentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("componentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("componentSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("componentId");

                    b.HasIndex("componentNumber")
                        .IsUnique();

                    b.ToTable("components");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Property<int>("criterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("criterionId"));

                    b.Property<string>("criterionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("criterionTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.HasKey("criterionId");

                    b.HasIndex("standardId", "criterionNumber")
                        .IsUnique();

                    b.ToTable("criteria");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.Property<int>("evidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("evidenceId"));

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<string>("evidenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("evidenceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("evidenceId");

                    b.HasIndex("complianceId");

                    b.ToTable("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Property<int>("functionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("functionId"));

                    b.Property<string>("functionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("functionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("functionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("functionId");

                    b.HasIndex("functionNumber")
                        .IsUnique();

                    b.ToTable("functions");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Property<int>("standardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("standardId"));

                    b.Property<int>("componentId")
                        .HasColumnType("integer");

                    b.Property<int>("functionId")
                        .HasColumnType("integer");

                    b.Property<string>("standardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("standardSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("standardTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("standardId");

                    b.HasIndex("componentId");

                    b.HasIndex("functionId");

                    b.HasIndex("standardNumber")
                        .IsUnique();

                    b.ToTable("standards");
                });

            modelBuilder.Entity("backend.Models.Location.District", b =>
                {
                    b.Property<int>("districtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("districtId"));

                    b.Property<string>("districtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("provinceId")
                        .HasColumnType("integer");

                    b.HasKey("districtId");

                    b.HasIndex("provinceId");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.Property<int>("provinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("provinceId"));

                    b.Property<string>("provinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("regionId")
                        .HasColumnType("integer");

                    b.HasKey("provinceId");

                    b.HasIndex("regionId");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("backend.Models.Location.Region", b =>
                {
                    b.Property<int>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("regionId"));

                    b.Property<string>("regionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("regionId");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyActionItem", b =>
                {
                    b.Property<int>("surveyActionItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyActionItemId"));

                    b.Property<string>("closureNotes")
                        .HasColumnType("text");

                    b.Property<int>("complianceAssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("correctiveAction")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("dueDate")
                        .HasColumnType("date");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("responsibleOfficer")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("surveyActionItemId");

                    b.HasIndex("complianceAssessmentId");

                    b.HasIndex("surveyId");

                    b.ToTable("surveyActionItems");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyReportVersion", b =>
                {
                    b.Property<int>("reportVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("reportVersionId"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("createdBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("reportJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<int>("versionNumber")
                        .HasColumnType("integer");

                    b.HasKey("reportVersionId");

                    b.HasIndex("surveyId", "versionNumber")
                        .IsUnique();

                    b.ToTable("surveyReportVersions");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyorReport", b =>
                {
                    b.Property<int>("surveyorReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyorReportId"));

                    b.Property<string>("goodPractices")
                        .HasColumnType("text");

                    b.Property<bool>("isSubmitted")
                        .HasColumnType("boolean");

                    b.Property<string>("notApplicableNotes")
                        .HasColumnType("text");

                    b.Property<string>("priorityFindings")
                        .HasColumnType("text");

                    b.Property<string>("recommendations")
                        .HasColumnType("text");

                    b.Property<DateTime?>("submittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("summary")
                        .HasColumnType("text");

                    b.Property<int>("surveyId")
                        .HasColumnType("integer");

                    b.Property<int>("surveyorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("surveyorReportId");

                    b.HasIndex("surveyorId");

                    b.HasIndex("surveyId", "surveyorId")
                        .IsUnique();

                    b.ToTable("surveyorReports");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyorReportReopen", b =>
                {
                    b.Property<int>("surveyorReportReopenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("surveyorReportReopenId"));

                    b.Property<DateTime?>("previousSubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("reopenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("reopenedByUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("surveyorReportId")
                        .HasColumnType("integer");

                    b.HasKey("surveyorReportReopenId");

                    b.HasIndex("surveyorReportId");

                    b.ToTable("surveyorReportReopens");
                });

            modelBuilder.Entity("backend.Models.Scoring.RiskRating", b =>
                {
                    b.Property<int>("riskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("riskId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("riskLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("riskValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("severityOrder")
                        .HasColumnType("integer");

                    b.HasKey("riskId");

                    b.ToTable("riskRatings");
                });

            modelBuilder.Entity("backend.Models.Scoring.Score", b =>
                {
                    b.Property<int>("scoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("scoreId"));

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("guidance")
                        .HasColumnType("text");

                    b.Property<string>("scoreLabel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("scoreValue")
                        .HasColumnType("integer");

                    b.HasKey("scoreId");

                    b.ToTable("scores");
                });

            modelBuilder.Entity("backend.Models.Accounts.RefreshToken", b =>
                {
                    b.HasOne("backend.Models.Accounts.UserAccount", "userAccount")
                        .WithMany("refreshTokens")
                        .HasForeignKey("userAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userAccount");
                });

            modelBuilder.Entity("backend.Models.Accounts.User", b =>
                {
                    b.HasOne("backend.Models.Facilities.Organization", "organization")
                        .WithMany("users")
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Accounts.UserAccount", "userAccount")
                        .WithOne("user")
                        .HasForeignKey("backend.Models.Accounts.User", "userAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");

                    b.Navigation("userAccount");
                });

            modelBuilder.Entity("backend.Models.Accounts.UserAccount", b =>
                {
                    b.HasOne("backend.Models.Accounts.Role", "role")
                        .WithMany("userAccounts")
                        .HasForeignKey("roleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("backend.Models.Assessment.ComplianceAssessment", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany()
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Scoring.RiskRating", "riskRating")
                        .WithMany("complianceAssessments")
                        .HasForeignKey("riskRatingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.Scoring.Score", "score")
                        .WithMany("complianceAssessments")
                        .HasForeignKey("scoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithMany("complianceAssessments")
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Surveyors", "surveyor")
                        .WithMany("complianceAssessments")
                        .HasForeignKey("surveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("compliance");

                    b.Navigation("riskRating");

                    b.Navigation("score");

                    b.Navigation("survey");

                    b.Navigation("surveyor");
                });

            modelBuilder.Entity("backend.Models.Assessment.ComplianceEvidenceCheck", b =>
                {
                    b.HasOne("backend.Models.Assessment.ComplianceAssessment", "complianceAssessment")
                        .WithMany("complianceEvidenceChecks")
                        .HasForeignKey("complianceAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Framework.Evidence", "evidence")
                        .WithMany()
                        .HasForeignKey("evidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("complianceAssessment");

                    b.Navigation("evidence");
                });

            modelBuilder.Entity("backend.Models.Facilities.Facility", b =>
                {
                    b.HasOne("backend.Models.Facilities.CreditationStatus", "creditationStatus")
                        .WithMany("facilities")
                        .HasForeignKey("creditationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Location.District", "district")
                        .WithMany("facilities")
                        .HasForeignKey("districtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Facilities.Level", "level")
                        .WithMany("facilities")
                        .HasForeignKey("levelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Facilities.Organization", "organization")
                        .WithMany("facilities")
                        .HasForeignKey("organizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("creditationStatus");

                    b.Navigation("district");

                    b.Navigation("level");

                    b.Navigation("organization");
                });

            modelBuilder.Entity("backend.Models.Facilities.Organization", b =>
                {
                    b.HasOne("backend.Models.Facilities.Category", "category")
                        .WithMany("organizations")
                        .HasForeignKey("categoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Survey", b =>
                {
                    b.HasOne("backend.Models.Facilities.Facility", "facility")
                        .WithMany("surveys")
                        .HasForeignKey("facilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyType", "surveyType")
                        .WithMany("surveys")
                        .HasForeignKey("surveyTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Surveyors", "surveyor")
                        .WithMany("surveys")
                        .HasForeignKey("surveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("facility");

                    b.Navigation("surveyType");

                    b.Navigation("surveyor");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyStandardAssignment", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany("surveyStandardAssignments")
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithMany("standardAssignments")
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Surveyors", "surveyor")
                        .WithMany("standardAssignments")
                        .HasForeignKey("surveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("standard");

                    b.Navigation("survey");

                    b.Navigation("surveyor");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", b =>
                {
                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithOne("toolkitSnapshot")
                        .HasForeignKey("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", "surveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("survey");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshotCompliance", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany()
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", "surveyToolkitSnapshot")
                        .WithMany("compliances")
                        .HasForeignKey("surveyToolkitSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compliance");

                    b.Navigation("surveyToolkitSnapshot");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshotStandard", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany()
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", "surveyToolkitSnapshot")
                        .WithMany("standards")
                        .HasForeignKey("surveyToolkitSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("standard");

                    b.Navigation("surveyToolkitSnapshot");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplate", b =>
                {
                    b.HasOne("backend.Models.Facilities.Level", "level")
                        .WithMany()
                        .HasForeignKey("levelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("level");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplateCompliance", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany()
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyToolkitTemplate", "surveyToolkitTemplate")
                        .WithMany("compliances")
                        .HasForeignKey("surveyToolkitTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compliance");

                    b.Navigation("surveyToolkitTemplate");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplateStandard", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany()
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyToolkitTemplate", "surveyToolkitTemplate")
                        .WithMany("standards")
                        .HasForeignKey("surveyToolkitTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("standard");

                    b.Navigation("surveyToolkitTemplate");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Surveyors", b =>
                {
                    b.HasOne("backend.Models.FaciltitySurvey.Specialization", "specialization")
                        .WithMany("surveyors")
                        .HasForeignKey("specializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.SurveyorCertStatus", "surveyorCertStatus")
                        .WithMany("surveyors")
                        .HasForeignKey("surveyorCertStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Accounts.User", "user")
                        .WithOne("surveyors")
                        .HasForeignKey("backend.Models.FaciltitySurvey.Surveyors", "userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("specialization");

                    b.Navigation("surveyorCertStatus");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.HasOne("backend.Models.Framework.Criterion", "criterion")
                        .WithMany("compliances")
                        .HasForeignKey("criterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("criterion");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany("criteria")
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("standard");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany("evidence")
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compliance");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.HasOne("backend.Models.Framework.Component", "component")
                        .WithMany("standards")
                        .HasForeignKey("componentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Framework.Function", "function")
                        .WithMany("standards")
                        .HasForeignKey("functionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("component");

                    b.Navigation("function");
                });

            modelBuilder.Entity("backend.Models.Location.District", b =>
                {
                    b.HasOne("backend.Models.Location.Province", "province")
                        .WithMany("districts")
                        .HasForeignKey("provinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("province");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.HasOne("backend.Models.Location.Region", "region")
                        .WithMany("provinces")
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("region");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyActionItem", b =>
                {
                    b.HasOne("backend.Models.Assessment.ComplianceAssessment", "complianceAssessment")
                        .WithMany()
                        .HasForeignKey("complianceAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithMany()
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("complianceAssessment");

                    b.Navigation("survey");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyReportVersion", b =>
                {
                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithMany()
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("survey");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyorReport", b =>
                {
                    b.HasOne("backend.Models.FaciltitySurvey.Survey", "survey")
                        .WithMany()
                        .HasForeignKey("surveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.FaciltitySurvey.Surveyors", "surveyor")
                        .WithMany()
                        .HasForeignKey("surveyorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("survey");

                    b.Navigation("surveyor");
                });

            modelBuilder.Entity("backend.Models.Reports.SurveyorReportReopen", b =>
                {
                    b.HasOne("backend.Models.Reports.SurveyorReport", "surveyorReport")
                        .WithMany()
                        .HasForeignKey("surveyorReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("surveyorReport");
                });

            modelBuilder.Entity("backend.Models.Accounts.Role", b =>
                {
                    b.Navigation("userAccounts");
                });

            modelBuilder.Entity("backend.Models.Accounts.User", b =>
                {
                    b.Navigation("surveyors");
                });

            modelBuilder.Entity("backend.Models.Accounts.UserAccount", b =>
                {
                    b.Navigation("refreshTokens");

                    b.Navigation("user");
                });

            modelBuilder.Entity("backend.Models.Assessment.ComplianceAssessment", b =>
                {
                    b.Navigation("complianceEvidenceChecks");
                });

            modelBuilder.Entity("backend.Models.Facilities.Category", b =>
                {
                    b.Navigation("organizations");
                });

            modelBuilder.Entity("backend.Models.Facilities.CreditationStatus", b =>
                {
                    b.Navigation("facilities");
                });

            modelBuilder.Entity("backend.Models.Facilities.Facility", b =>
                {
                    b.Navigation("surveys");
                });

            modelBuilder.Entity("backend.Models.Facilities.Level", b =>
                {
                    b.Navigation("facilities");
                });

            modelBuilder.Entity("backend.Models.Facilities.Organization", b =>
                {
                    b.Navigation("facilities");

                    b.Navigation("users");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Specialization", b =>
                {
                    b.Navigation("surveyors");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Survey", b =>
                {
                    b.Navigation("complianceAssessments");

                    b.Navigation("standardAssignments");

                    b.Navigation("toolkitSnapshot");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitSnapshot", b =>
                {
                    b.Navigation("compliances");

                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyToolkitTemplate", b =>
                {
                    b.Navigation("compliances");

                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyType", b =>
                {
                    b.Navigation("surveys");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.SurveyorCertStatus", b =>
                {
                    b.Navigation("surveyors");
                });

            modelBuilder.Entity("backend.Models.FaciltitySurvey.Surveyors", b =>
                {
                    b.Navigation("complianceAssessments");

                    b.Navigation("standardAssignments");

                    b.Navigation("surveys");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Navigation("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Navigation("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Navigation("criteria");

                    b.Navigation("surveyStandardAssignments");
                });

            modelBuilder.Entity("backend.Models.Location.District", b =>
                {
                    b.Navigation("facilities");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.Navigation("districts");
                });

            modelBuilder.Entity("backend.Models.Location.Region", b =>
                {
                    b.Navigation("provinces");
                });

            modelBuilder.Entity("backend.Models.Scoring.RiskRating", b =>
                {
                    b.Navigation("complianceAssessments");
                });

            modelBuilder.Entity("backend.Models.Scoring.Score", b =>
                {
                    b.Navigation("complianceAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
