// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260806025748_functionComponentModelsEdits")]
    partial class functionComponentModelsEdits
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Property<int>("complianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("complianceId"));

                    b.Property<string>("complianceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("criterionId")
                        .HasColumnType("integer");

                    b.Property<bool>("isApplicable")
                        .HasColumnType("boolean");

                    b.HasKey("complianceId");

                    b.HasIndex("criterionId");

                    b.ToTable("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Property<int>("componentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("componentId"));

                    b.Property<string>("componentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("componentSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("componentId");

                    b.ToTable("components");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Property<int>("criterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("criterionId"));

                    b.Property<string>("criterionTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("isApplicable")
                        .HasColumnType("boolean");

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.HasKey("criterionId");

                    b.HasIndex("standardId");

                    b.ToTable("criteria");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.Property<int>("evidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("evidenceId"));

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<string>("evidenceSumaary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isApplicable")
                        .HasColumnType("boolean");

                    b.HasKey("evidenceId");

                    b.HasIndex("complianceId");

                    b.ToTable("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Property<int>("functionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("functionId"));

                    b.Property<string>("functionSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("functiontTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("functionId");

                    b.ToTable("functions");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Property<int>("standardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("standardId"));

                    b.Property<int>("componentId")
                        .HasColumnType("integer");

                    b.Property<int>("functionId")
                        .HasColumnType("integer");

                    b.Property<string>("standardTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("standardId");

                    b.HasIndex("componentId");

                    b.HasIndex("functionId");

                    b.ToTable("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.HasOne("backend.Models.Framework.Criterion", "criterion")
                        .WithMany("compliances")
                        .HasForeignKey("criterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("criterion");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany("criteria")
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("standard");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany("evidence")
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compliance");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.HasOne("backend.Models.Framework.Component", "component")
                        .WithMany("standards")
                        .HasForeignKey("componentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Framework.Function", "function")
                        .WithMany("standards")
                        .HasForeignKey("functionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("component");

                    b.Navigation("function");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Navigation("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Navigation("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Navigation("criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
