// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820053902_UpdateDeleteBehaviours")]
    partial class UpdateDeleteBehaviours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Property<int>("complianceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("complianceId"));

                    b.Property<string>("complianceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("complianceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("criterionId")
                        .HasColumnType("integer");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("complianceId");

                    b.HasIndex("criterionId", "complianceNumber")
                        .IsUnique();

                    b.ToTable("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Property<int>("componentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("componentId"));

                    b.Property<string>("componentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("componentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("componentSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("componentId");

                    b.HasIndex("componentNumber")
                        .IsUnique();

                    b.ToTable("components");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Property<int>("criterionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("criterionId"));

                    b.Property<string>("criterionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("criterionTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("standardId")
                        .HasColumnType("integer");

                    b.HasKey("criterionId");

                    b.HasIndex("standardId", "criterionNumber")
                        .IsUnique();

                    b.ToTable("criteria");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.Property<int>("evidenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("evidenceId"));

                    b.Property<int>("complianceId")
                        .HasColumnType("integer");

                    b.Property<string>("evidenceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("evidenceSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("isApplicable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("evidenceId");

                    b.HasIndex("complianceId");

                    b.ToTable("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Property<int>("functionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("functionId"));

                    b.Property<string>("functionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("functionSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("functionTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("functionId");

                    b.HasIndex("functionNumber")
                        .IsUnique();

                    b.ToTable("functions");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Property<int>("standardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("standardId"));

                    b.Property<int>("componentId")
                        .HasColumnType("integer");

                    b.Property<int>("functionId")
                        .HasColumnType("integer");

                    b.Property<string>("standardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("standardSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("standardTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("standardId");

                    b.HasIndex("componentId");

                    b.HasIndex("functionId");

                    b.HasIndex("standardNumber")
                        .IsUnique();

                    b.ToTable("standards");
                });

            modelBuilder.Entity("backend.Models.Location.District", b =>
                {
                    b.Property<int>("districtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("districtId"));

                    b.Property<string>("districtName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("provinceId")
                        .HasColumnType("integer");

                    b.HasKey("districtId");

                    b.HasIndex("provinceId");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.Property<int>("provinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("provinceId"));

                    b.Property<string>("provinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("regionId")
                        .HasColumnType("integer");

                    b.HasKey("provinceId");

                    b.HasIndex("regionId");

                    b.ToTable("provinces");
                });

            modelBuilder.Entity("backend.Models.Location.Region", b =>
                {
                    b.Property<int>("regionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("regionId"));

                    b.Property<string>("regionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("regionId");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.HasOne("backend.Models.Framework.Criterion", "criterion")
                        .WithMany("compliances")
                        .HasForeignKey("criterionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("criterion");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.HasOne("backend.Models.Framework.Standard", "standard")
                        .WithMany("criteria")
                        .HasForeignKey("standardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("standard");
                });

            modelBuilder.Entity("backend.Models.Framework.Evidence", b =>
                {
                    b.HasOne("backend.Models.Framework.Compliance", "compliance")
                        .WithMany("evidence")
                        .HasForeignKey("complianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("compliance");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.HasOne("backend.Models.Framework.Component", "component")
                        .WithMany("standards")
                        .HasForeignKey("componentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Framework.Function", "function")
                        .WithMany("standards")
                        .HasForeignKey("functionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("component");

                    b.Navigation("function");
                });

            modelBuilder.Entity("backend.Models.Location.District", b =>
                {
                    b.HasOne("backend.Models.Location.Province", "province")
                        .WithMany("districts")
                        .HasForeignKey("provinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("province");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.HasOne("backend.Models.Location.Region", "region")
                        .WithMany("provinces")
                        .HasForeignKey("regionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("region");
                });

            modelBuilder.Entity("backend.Models.Framework.Compliance", b =>
                {
                    b.Navigation("evidence");
                });

            modelBuilder.Entity("backend.Models.Framework.Component", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Criterion", b =>
                {
                    b.Navigation("compliances");
                });

            modelBuilder.Entity("backend.Models.Framework.Function", b =>
                {
                    b.Navigation("standards");
                });

            modelBuilder.Entity("backend.Models.Framework.Standard", b =>
                {
                    b.Navigation("criteria");
                });

            modelBuilder.Entity("backend.Models.Location.Province", b =>
                {
                    b.Navigation("districts");
                });

            modelBuilder.Entity("backend.Models.Location.Region", b =>
                {
                    b.Navigation("provinces");
                });
#pragma warning restore 612, 618
        }
    }
}
