import { compareScope, isHighRisk, isPriorityFinding, summariseReport } from "../../utils/surveyReports";

export function ExecutiveSummary({ report }) {
  const stats = summariseReport(report.items);
  const completion = stats.total ? Math.round((stats.scored + stats.notApplicable) / stats.total * 100) : 0;
  const priorities = report.items.filter(isPriorityFinding).sort((a,b) => Number(isHighRisk(b)) - Number(isHighRisk(a)) || (b.riskSeverity || 0) - (a.riskSeverity || 0) || (a.scoreValue ?? 5) - (b.scoreValue ?? 5));
  const comparison = compareScope(report.items, report.internalItems || []);
  return <section id="report-executive" className="report-executive"><h2>Executive summary</h2><div className="report-executive-metrics"><div><strong>{completion}%</strong><span>Assessment completion</span></div><div><strong>{stats.score == null ? "Not scored" : `${stats.score}%`}</strong><span>{stats.unassessed ? "Provisional score" : "Overall score"}</span></div><div><strong>{report.items.filter(isHighRisk).length}</strong><span>High / extreme risks</span></div><div><strong>{priorities.length}</strong><span>Findings needing attention</span></div></div><p>{stats.unassessed ? `${stats.unassessed} requirements remain unassessed. Results are provisional.` : "All selected requirements have a score or are not applicable."} {stats.notApplicable} not applicable.</p>{report.survey.surveyType === "External" && <p>{comparison.compared ? `${comparison.differing} of ${comparison.compared} comparable requirements have different internal and external scores. External minus internal: ${comparison.delta > 0 ? "+" : ""}${comparison.delta} percentage points, calculated on matched, assessed, applicable requirements only.` : "No matched, assessed and applicable requirements are available for score comparison."}</p>}<h3>Priority gaps</h3>{priorities.length ? <ol className="report-priority-list">{priorities.slice(0,5).map((item) => <li key={item.complianceId}><strong>{item.complianceNumber}</strong> · {item.criterionTitle} — {item.riskLabel || "Risk not rated"}<p>{item.complianceComments ? item.complianceComments.slice(0,180) + (item.complianceComments.length > 180 ? "…" : "") : "No findings comment recorded."}</p></li>)}</ol> : <p>No poor- or fair-achievement findings with high or extreme risk in the selected scope.</p>}{priorities.length > 5 && <p className="report-method">Showing the five highest-priority gaps. See detailed findings for the remaining {priorities.length - 5}.</p>}</section>;
}

export function Recommendations({ report }) {
  return <section id="report-recommendations" className="report-recommendations"><h2>Recommendations and sign-off</h2>{report.actions?.length ? <table><thead><tr><th>Compliance</th><th>Recommended action</th><th>Responsible officer</th><th>Due date</th></tr></thead><tbody>{report.actions.map((action) => <tr key={action.complianceId}><td>{report.items.find((item) => item.complianceId === action.complianceId)?.complianceNumber || "—"}</td><td className="report-text">{action.recommendation}</td><td>{action.owner || "To be assigned"}</td><td>{action.dueDate || "To be agreed"}</td></tr>)}</tbody></table> : <p>No recommendations entered.</p>}<div className="report-signoff"><p><strong>Prepared for review by:</strong> {report.reviewerName || "________________________"}</p><p className="report-text">{report.reviewNotes || "Review notes: __________________________________________________"}</p><p>Reviewer signature: ________________________ &nbsp; Date: __________________</p><p className="report-method">Unsigned — reviewer approval must be recorded separately. Saving a version does not approve the report.</p></div></section>;
}

export function ReportContents({ report, standards }) {
  return <nav className="report-contents" aria-label="Report contents"><h2>Contents</h2><ul>{report.included.includes("summary") && <li><a href="#report-executive">Executive summary</a></li>}{report.included.includes("standards") && <li><a href="#report-standard-scores">Scores by standard</a></li>}{(report.included.includes("findings") || report.included.includes("evidence")) && standards.map((s) => <li key={s.id}><a href={`#report-standard-${s.id}`}>{s.number} · {s.title}</a></li>)}{report.included.includes("actions") && <li><a href="#report-recommendations">Recommendations and sign-off</a></li>}</ul></nav>;
}
