import { Link } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { getReportSurveys, getSubmittedSurveyorReports, getSurveyActions } from "../../api/api";
import { useAuth } from "../../context/AuthContext";

const formatDate = (value) => value ? new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" }) : "Not submitted";

export default function ReportsCentrePage() {
  const { auth } = useAuth();
  const [surveys, setSurveys] = useState([]); const [handovers, setHandovers] = useState([]); const [actions, setActions] = useState([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  useEffect(() => {
    let active = true;
    const load = async () => {
      const results = await Promise.allSettled([getReportSurveys(), getSubmittedSurveyorReports(), getSurveyActions()]);
      if (!active) return;
      const [surveysResult, handoversResult, actionsResult] = results;
      if (surveysResult.status === "fulfilled") setSurveys(surveysResult.value.data);
      if (handoversResult.status === "fulfilled") setHandovers(handoversResult.value.data);
      if (actionsResult.status === "fulfilled") setActions(actionsResult.value.data);
      if (results.some((result) => result.status === "rejected")) setError("One reporting section could not be loaded. The remaining information is still available.");
      setLoading(false);
    };
    load();
    return () => { active = false; };
  }, []);
  const actionCounts = useMemo(() => ({ open: actions.filter((item) => item.status === "Open").length, progress: actions.filter((item) => item.status === "In progress").length, closed: actions.filter((item) => item.status === "Closed").length }), [actions]);
  const isLead = auth?.roleName === "Team Lead";
  return <main className="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:py-8"><header className="overflow-hidden rounded-2xl border border-[#c9dded] bg-[linear-gradient(125deg,#eaf3fb_0%,#f8fafc_60%,#fdf7ea_100%)] p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#16803a]">Reporting workspace</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-[#092a5a]">Reports Centre</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#4b5f7a]">{isLead ? "Review surveyor handovers, track corrective actions, and prepare formal reports for surveys you lead." : "Prepare formal reports, review submitted handovers, and monitor corrective actions across the accreditation programme."}</p></header>{error && <p role="alert" className="mt-5 rounded-lg border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">{error}</p>}
    <section className="mt-6 grid items-stretch gap-6 md:grid-cols-3" aria-label="Report tools"><ToolCard eyebrow="Formal reporting" title="Build a survey report" detail="Select standards, include results and findings, then save an immutable report version." to="/reports/survey" action="Build report" /><ToolCard eyebrow="Corrective actions" title="Action register" detail="Assign owners, set due dates, and follow priority findings through to closure." to="/reports/actions" action="Open register" /><ToolCard eyebrow="Survey results" title="Results workspace" detail="Open the survey-level dashboard for component, standard, risk and scoring detail." to="/surveys" action="View surveys" /></section>
    <section className="reports-centre-secondary-grid mt-6"><article className="overflow-hidden rounded-xl border border-[#dbe5ef] bg-white shadow-sm"><div className="flex items-end justify-between gap-4 border-b border-[#dbe5ef] px-5 py-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#16803a]">Surveyor handovers</p><h2 className="mt-1 text-lg font-bold text-[#092a5a]">Submitted reports</h2></div><span className="rounded-full bg-[#edf8f0] px-2.5 py-1 text-xs font-bold text-[#16803a]">{loading ? "…" : handovers.length}</span></div>{loading ? <div className="space-y-3 p-5">{[1,2,3].map((key) => <div key={key} className="h-16 animate-pulse rounded-lg bg-slate-100" />)}</div> : handovers.length ? <div className="divide-y divide-[#e7edf4]">{handovers.slice(0, 6).map((report) => <article key={report.surveyorReportId} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#16803a]">{report.facilityName} · {report.surveyType}</p><h3 className="mt-1 font-semibold text-[#092a5a]">{report.surveyorName}</h3><p className="mt-1 text-sm text-[#4b5f7a]">Submitted {formatDate(report.submittedAt)} · {report.scoredRequirements} of {report.assignedRequirements} requirements scored</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-[#385273]">{report.summary || "No overall summary recorded."}</p></div><Link className="shrink-0 rounded-lg border border-[#c5d5e8] bg-white px-3 py-2 text-center text-xs font-semibold text-[#16803a] hover:bg-[#edf8f0]" to={`/surveys/${report.surveyId}/team-dashboard`}>Review handover</Link></article>)}</div> : <p className="p-5 text-sm text-[#68778c]">No submitted surveyor handovers are available for your surveys yet.</p>}</article>
      <aside className="flex h-full min-h-72 flex-col overflow-hidden rounded-xl border border-[#dbe5ef] bg-white shadow-sm"><div className="border-b border-[#b8d9d3] bg-[#f3faf8] px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#16803a]">Corrective actions</p><h2 className="mt-1 text-lg font-bold text-[#092a5a]">Action status</h2></div><dl className="divide-y divide-[#e7edf4] px-5">{[["Open", actionCounts.open, "text-red-700"], ["In progress", actionCounts.progress, "text-amber-800"], ["Closed", actionCounts.closed, "text-[#16803a]"]].map(([label, count, tone]) => <div key={label} className="flex items-center justify-between py-4"><dt className="text-sm text-[#4b5f7a]">{label}</dt><dd className={`text-2xl font-bold ${tone}`}>{loading ? "…" : count}</dd></div>)}</dl><Link to="/reports/actions" className="m-5 mt-auto inline-block text-sm font-semibold text-[#16803a] hover:underline">Open corrective action register →</Link></aside></section>
    <section className="mt-6 overflow-hidden rounded-xl border border-[#dbe5ef] bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-[#dbe5ef] px-5 py-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#16803a]">Report scope</p><h2 className="mt-1 text-lg font-bold text-[#092a5a]">Available surveys</h2></div><Link to="/surveys" className="text-sm font-semibold text-[#16803a] hover:underline">Open survey workspace →</Link></div><div className="divide-y divide-[#e7edf4]">{surveys.map((survey) => <div key={survey.surveyId} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-[#092a5a]">{survey.facilityName}</p><p className="mt-1 text-sm text-[#4b5f7a]">{survey.surveyType} survey · {survey.startDate} — {survey.endDate}{survey.isCancelled ? " · Cancelled" : ""}</p></div><div className="flex gap-2"><Link to={`/surveys/${survey.surveyId}/results`} className="rounded-lg border border-[#c5d5e8] px-3 py-2 text-xs font-semibold text-[#16803a] hover:bg-[#edf8f0]">Results</Link><Link to={`/reports/survey?survey=${survey.surveyId}`} className="rounded-lg bg-[#16803a] px-3 py-2 text-xs font-semibold text-white hover:bg-[#0d6531]">Report</Link></div></div>)}</div></section>
  </main>;
}

function ToolCard({ eyebrow, title, detail, to, action }) { return <article className="flex h-full min-h-52 flex-col rounded-xl border border-[#b8d9d3] bg-[#f3faf8] p-5 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#16803a]">{eyebrow}</p><h2 className="mt-2 text-xl font-bold text-[#092a5a]">{title}</h2><p className="mt-2 text-sm leading-6 text-[#4b5f7a]">{detail}</p><Link to={to} className="mt-auto pt-5 text-sm font-semibold text-[#16803a] hover:underline">{action} →</Link></article>; }
