import { Link, useSearchParams } from "react-router-dom";
import { useEffect, useMemo, useState } from "react";
import { createSurveyAction, getReportSurveys, getSurveyActionSummary, getSurveyActions, getSurveyReport, updateSurveyAction } from "../../api/api";
import FormModal from "../../components/FormModal";
import Pagination from "../../components/Pagination";
import useUnsavedChanges from "../../hooks/useUnsavedChanges";
import { compareReferenceNumber } from "../../utils/numberSort";

const priority = (item) => item.scoreValue != null && item.scoreValue <= 2 && (item.riskSeverity >= 3 || /^(high|extreme)$/i.test(item.riskLabel || ""));
const blank = { recommendation: "", correctiveAction: "", responsibleOfficer: "", dueDate: "", status: "Open", closureNotes: "" };
const emptyFilters = { facilityId: "", status: "", owner: "", risk: "", overdue: false };
const csvValue = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
const savedFilters = () => { try { const saved = JSON.parse(localStorage.getItem("action-plan-filters") || "{}"); const facilityId = Number.parseInt(saved.facilityId, 10); return { ...emptyFilters, ...saved, facilityId: Number.isInteger(facilityId) && facilityId > 0 ? String(facilityId) : "" }; } catch { return emptyFilters; } };

export default function SurveyActionPlanPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const [surveys, setSurveys] = useState([]); const [surveyId, setSurveyId] = useState(() => searchParams.get("survey") || localStorage.getItem("action-plan-survey") || "");
  const [items, setItems] = useState([]); const [report, setReport] = useState(null);
  const [editor, setEditor] = useState(null); const [form, setForm] = useState(blank);
  const [editorInitial, setEditorInitial] = useState(blank);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const [page, setPage] = useState(1); const [total, setTotal] = useState(0);
  const [filters, setFilters] = useState(() => ({ ...savedFilters(), facilityId: searchParams.get("facility") || savedFilters().facilityId, status: searchParams.get("status") || "", owner: searchParams.get("owner") || "", risk: searchParams.get("risk") || "", overdue: searchParams.get("overdue") === "true" }));
  const [summary, setSummary] = useState({ total: 0, open: 0, inProgress: 0, closed: 0, overdue: 0 });
  const queryParams = (requestedPage) => { const facilityId = Number.parseInt(filters.facilityId, 10); return { ...(surveyId ? { surveyId } : {}), ...(Number.isInteger(facilityId) && facilityId > 0 ? { facilityId } : {}), ...(filters.status ? { status: filters.status } : {}), ...(filters.owner.trim() ? { owner: filters.owner.trim() } : {}), ...(filters.risk ? { risk: filters.risk } : {}), ...(filters.overdue ? { overdue: true } : {}), ...(requestedPage ? { page: requestedPage, pageSize: 10 } : {}) }; };
  const loadActions = async (requestedPage = page) => { const { data } = await getSurveyActions(queryParams(requestedPage)); setItems(data.items); setTotal(data.total); };
  const loadSummary = async () => { const { data } = await getSurveyActionSummary(queryParams()); setSummary(data); };
  useEffect(() => { getReportSurveys().then(({ data }) => setSurveys([...data].sort((first, second) => compareReferenceNumber(first.surveyId, second.surveyId)))).catch(() => setError("Could not load surveys available to you.")).finally(() => setLoading(false)); }, []);
  useEffect(() => { localStorage.setItem("action-plan-survey", surveyId); }, [surveyId]);
  useEffect(() => { localStorage.setItem("action-plan-filters", JSON.stringify(filters)); }, [filters]);
  useEffect(() => {
    const next = new URLSearchParams();
    if (surveyId) next.set("survey", surveyId);
    if (filters.facilityId) next.set("facility", filters.facilityId);
    if (filters.status) next.set("status", filters.status);
    if (filters.owner) next.set("owner", filters.owner);
    if (filters.risk) next.set("risk", filters.risk);
    if (filters.overdue) next.set("overdue", "true");
    setSearchParams(next, { replace: true });
  }, [surveyId, filters, setSearchParams]);
  useEffect(() => { setPage(1); setEditor(null); Promise.all([loadActions(1), loadSummary()]).catch(() => setError("Could not load action plans.")); }, [surveyId, filters]);
  useEffect(() => { setReport(null); if (surveyId) getSurveyReport(surveyId).then(({ data }) => setReport(data)).catch(() => setError("Could not load priority findings for this survey.")); }, [surveyId]);
  const selectedSurvey = surveys.find((survey) => String(survey.surveyId) === String(surveyId));
  const findings = useMemo(() => {
    const facilityMatches = !filters.facilityId || String(selectedSurvey?.facilityId) === String(filters.facilityId);
    return facilityMatches
      ? (report?.items || []).filter((item) => priority(item) && (!filters.risk || item.riskLabel === filters.risk))
      : [];
  }, [report, selectedSurvey, filters.facilityId, filters.risk]);
  const openNew = (finding) => { const next = { ...blank, recommendation: finding.complianceComments || "" }; setEditor({ finding }); setForm(next); setEditorInitial(next); };
  const openEdit = (item) => { const next = { recommendation: item.recommendation || "", correctiveAction: item.correctiveAction || "", responsibleOfficer: item.responsibleOfficer || "", dueDate: item.dueDate || "", status: item.status, closureNotes: item.closureNotes || "" }; setEditor({ item }); setForm(next); setEditorInitial(next); };
  const save = async () => { setSaving(true); setError(""); try { if (editor.item) await updateSurveyAction(editor.item.surveyActionItemId, form); else await createSurveyAction({ surveyId: Number(surveyId), complianceAssessmentId: editor.finding.complianceAssessmentId, ...form }); await Promise.all([loadActions(), loadSummary()]); setEditor(null); } catch (e) { setError(e.response?.data || "Could not save the action plan item."); } finally { setSaving(false); } };
  useUnsavedChanges(Boolean(editor) && JSON.stringify(form) !== JSON.stringify(editorInitial));
  const changePage = (nextPage) => { setPage(nextPage); loadActions(nextPage).catch(() => setError("Could not load that page of action items.")); };
  const exportCsv = async () => { try { const { data } = await getSurveyActions(queryParams()); const rows = [ ["Facility", "Survey type", "Requirement", "Summary", "Outcome", "Risk", "Recommendation", "Corrective action", "Owner", "Due date", "Status", "Closure notes"], ...data.map((item) => [item.facilityName, item.surveyType, item.complianceNumber, item.complianceSummary, item.outcome, item.riskRating, item.recommendation, item.correctiveAction, item.responsibleOfficer, item.dueDate, item.status, item.closureNotes]) ]; const blob = new Blob([rows.map((row) => row.map(csvValue).join(",")).join("\n")], { type: "text/csv;charset=utf-8" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = "corrective-action-register.csv"; link.click(); URL.revokeObjectURL(link.href); } catch { setError("Could not export the filtered action register."); } };
  return <main className="action-plan-page mx-auto max-w-7xl px-4 py-6 sm:px-6"><header className="rounded-2xl border border-[#c9dded] bg-[linear-gradient(125deg,#eaf3fb_0%,#f8fafc_65%,#fdf7ea_100%)] p-6 sm:p-8"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#16803a]">Reports centre</p><h1 className="mt-2 text-3xl font-bold text-[#092a5a]">Corrective action register</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#4b5f7a]">Turn high-priority survey findings into owned actions and track them through to closure.</p></div><div className="print:hidden flex flex-wrap gap-2"><button type="button" onClick={() => window.print()} className="rounded-lg border border-[#c5d5e8] bg-white px-4 py-2.5 text-sm font-semibold text-[#16803a] hover:bg-[#edf8f0]">Print / Save PDF</button><button type="button" onClick={exportCsv} className="rounded-lg border border-[#c5d5e8] bg-white px-4 py-2.5 text-sm font-semibold text-[#16803a] hover:bg-[#edf8f0]">Export CSV</button><Link to="/reports" className="rounded-lg border border-[#c5d5e8] bg-white px-4 py-2.5 text-center text-sm font-semibold text-[#16803a] hover:bg-[#edf8f0]">Reports Centre</Link></div></div></header>
    {error && <p role="alert" className="mt-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    <section className="action-plan-controls mt-6 rounded-xl border border-[#dbe5ef] bg-white p-5 shadow-sm"><div className="flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#16803a]">Filter the register</p><h2 className="mt-1 text-lg font-bold text-[#092a5a]">Action plan filters</h2></div><button type="button" onClick={() => { setSurveyId(""); setFilters(emptyFilters); }} className="print:hidden text-sm font-semibold text-[#16803a] hover:underline">Clear filters</button></div><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Filter label="Survey"><select value={surveyId} onChange={(e) => setSurveyId(e.target.value)}><option value="">All surveys</option>{surveys.map((survey) => <option key={survey.surveyId} value={survey.surveyId}>{survey.facilityName} · {survey.surveyType} · #{survey.surveyId}</option>)}</select></Filter><Filter label="Facility"><select value={filters.facilityId} onChange={(e) => setFilters((current) => ({ ...current, facilityId: e.target.value }))}><option value="">All facilities</option>{[...new Map(surveys.filter((survey) => Number.isInteger(Number(survey.facilityId))).map((survey) => [survey.facilityId, survey.facilityName])).entries()].map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></Filter><Filter label="Status"><select value={filters.status} onChange={(e) => setFilters((current) => ({ ...current, status: e.target.value }))}><option value="">All statuses</option><option>Open</option><option>In progress</option><option>Closed</option></select></Filter><Filter label="Risk"><select value={filters.risk} onChange={(e) => setFilters((current) => ({ ...current, risk: e.target.value }))}><option value="">All risks</option><option>Low</option><option>Medium</option><option>High</option><option>Extreme</option></select></Filter><Filter label="Responsible officer"><input value={filters.owner} onChange={(e) => setFilters((current) => ({ ...current, owner: e.target.value }))} placeholder="Search owner" /></Filter><label className="flex items-end gap-3 pb-2 text-sm font-semibold text-[#092a5a]"><input type="checkbox" checked={filters.overdue} onChange={(e) => setFilters((current) => ({ ...current, overdue: e.target.checked }))} className="h-4 w-4 accent-[#16803a]" />Overdue only</label></div></section>
    <section className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5" aria-label="Action plan status"><Stat label="Total" value={summary.total} /><Stat label="Open" value={summary.open} tone="text-red-700" /><Stat label="In progress" value={summary.inProgress} tone="text-amber-800" /><Stat label="Closed" value={summary.closed} tone="text-[#16803a]" /><Stat label="Overdue" value={summary.overdue} tone="text-red-700" /></section>
    <section className="mt-6 overflow-hidden rounded-xl border border-[#dbe5ef] bg-white shadow-sm"><div className="border-b border-[#dbe5ef] px-5 py-4"><h2 className="font-bold text-[#092a5a]">Current actions</h2><p className="mt-1 text-sm text-[#4b5f7a]">{total} recorded action{total === 1 ? "" : "s"}{loading ? " · loading…" : ""}</p></div>{items.length ? <div className="divide-y divide-[#e7edf4]">{items.map((item) => <article key={item.surveyActionItemId} className="p-5"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#16803a]">{item.facilityName} · {item.complianceNumber}</p><h3 className="mt-1 text-justify font-semibold text-[#092a5a]">{item.complianceSummary}</h3><div className="mt-3 flex flex-wrap gap-2 text-xs font-semibold"><span className="rounded-full bg-slate-100 px-2 py-1 text-slate-700">{item.outcome || "Not scored"}</span><span className="rounded-full bg-red-50 px-2 py-1 text-red-700">{item.riskRating || "No risk"} risk</span></div><p className="mt-3 text-sm text-[#385273]"><b>Recommendation:</b> {item.recommendation}</p>{item.correctiveAction && <p className="mt-1 text-sm text-[#385273]"><b>Corrective action:</b> {item.correctiveAction}</p>}<p className="mt-2 text-xs text-[#68778c]">Owner: {item.responsibleOfficer || "Unassigned"} · Due: {item.dueDate || "Not set"}</p></div><div className="action-plan-edit flex shrink-0 items-start gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${item.status === "Closed" ? "bg-[#edf8f0] text-[#16803a]" : item.status === "In progress" ? "bg-amber-50 text-amber-800" : "bg-red-50 text-red-700"}`}>{item.status}</span><button onClick={() => openEdit(item)} className="rounded-lg border border-[#c5d5e8] bg-white px-3 py-1.5 text-xs font-semibold text-[#16803a] hover:bg-[#edf8f0]">Update</button></div></div></article>)}</div> : <p className="p-5 text-sm text-[#68778c]">No action items match this view yet.</p>}<Pagination page={page} total={total} onPageChange={changePage} /></section>
    {surveyId && report && <section className="mt-6 overflow-hidden rounded-xl border border-[#ead7a3] bg-white shadow-sm"><div className="border-b border-[#ead7a3] bg-[#fffbf0] px-5 py-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#9a5b13]">Priority findings</p><h2 className="mt-1 font-bold text-[#092a5a]">Create actions from urgent findings</h2><p className="mt-1 text-xs text-[#735b21]">This list follows the selected survey, facility, and risk filters.</p></div>{findings.length ? <div className="divide-y divide-[#f0e4c2]">{findings.map((finding) => <article key={finding.complianceAssessmentId} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#9a5b13]">{finding.complianceNumber} · {finding.scoreLabel} · {finding.riskLabel} risk</p><p className="mt-1 text-sm leading-6 text-[#385273]">{finding.complianceSummary}</p></div><button onClick={() => openNew(finding)} className="shrink-0 rounded-lg bg-[#16803a] px-3 py-2 text-xs font-semibold text-white hover:bg-[#0d6531]">Create action</button></article>)}</div> : <p className="p-5 text-sm text-[#4b5f7a]">No urgent findings match the selected survey, facility, and risk filters.</p>}</section>}
    <FormModal open={!!editor} title={editor?.item ? "Update action item" : "Create corrective action"} onClose={() => !saving && setEditor(null)}><div className="grid gap-4">{[["Recommendation", "recommendation", true], ["Corrective action", "correctiveAction"], ["Responsible officer", "responsibleOfficer"]].map(([label, key, required]) => <label key={key} className="text-sm font-semibold text-[#092a5a]">{label}<textarea required={required} value={form[key]} onChange={(e) => setForm((current) => ({ ...current, [key]: e.target.value }))} rows="3" className="mt-1.5 w-full resize-none rounded-lg border border-[#c5d5e8] px-3 py-2 text-sm font-normal" /></label>)}<div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold text-[#092a5a]">Due date<input type="date" value={form.dueDate} onChange={(e) => setForm((current) => ({ ...current, dueDate: e.target.value }))} className="mt-1.5 w-full rounded-lg border border-[#c5d5e8] px-3 py-2 text-sm font-normal" /></label>{editor?.item && <label className="text-sm font-semibold text-[#092a5a]">Status<select value={form.status} onChange={(e) => setForm((current) => ({ ...current, status: e.target.value }))} className="mt-1.5 w-full rounded-lg border border-[#c5d5e8] px-3 py-2 text-sm font-normal"><option>Open</option><option>In progress</option><option>Closed</option></select></label>}</div>{editor?.item && <label className="text-sm font-semibold text-[#092a5a]">Closure notes<textarea value={form.closureNotes} onChange={(e) => setForm((current) => ({ ...current, closureNotes: e.target.value }))} rows="3" className="mt-1.5 w-full resize-none rounded-lg border border-[#c5d5e8] px-3 py-2 text-sm font-normal" /></label>}<div className="flex justify-end gap-3"><button type="button" onClick={() => setEditor(null)} className="rounded-lg border border-[#c5d5e8] px-4 py-2 text-sm font-semibold text-[#4b5f7a]">Cancel</button><button type="button" disabled={saving || !form.recommendation.trim()} onClick={save} className="rounded-lg bg-[#16803a] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save action"}</button></div></div></FormModal>
  </main>;
}

function Filter({ label, children }) { return <label className="block text-sm font-semibold text-[#092a5a]">{label}<span className="mt-1.5 block [&_input]:w-full [&_input]:rounded-lg [&_input]:border [&_input]:border-[#c5d5e8] [&_input]:px-3 [&_input]:py-2.5 [&_input]:text-sm [&_input]:font-normal [&_select]:w-full [&_select]:rounded-lg [&_select]:border [&_select]:border-[#c5d5e8] [&_select]:bg-white [&_select]:px-3 [&_select]:py-2.5 [&_select]:text-sm [&_select]:font-normal">{children}</span></label>; }
function Stat({ label, value, tone = "text-[#092a5a]" }) { return <article className="rounded-xl border border-[#dbe5ef] bg-white px-4 py-3 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#68778c]">{label}</p><p className={`mt-1 text-2xl font-bold ${tone}`}>{value}</p></article>; }
